### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by 910JQK** [SubwayDesktop/subway-panel#1]
[  9%] Generating window-list.moc
[ 18%] Generating panelapplication.moc
[ 27%] Generating applet.moc
[ 36%] Generating instanceofwindow.moc
[ 45%] Generating subway-panel.moc
Scanning dependencies of target subway-panel
[ 54%] Building CXX object CMakeFiles/subway-panel.dir/panelapplication.cpp.o
[ 63%] Building CXX object CMakeFiles/subway-panel.dir/applet.cpp.o
[ 72%] Building CXX object CMakeFiles/subway-panel.dir/applets/window-list/instanceofwindow.cpp.o
In file included from /usr/include/X11/Xlib.h:44:0,
                 from /home/jqk/ProjectFiles/Remote/subway-panel/applets/window-list/instanceofwindow.h:26,
                 from /home/jqk/ProjectFiles/Remote/subway-panel/applets/window-list/window-list.h:28,
                 from /home/jqk/ProjectFiles/Remote/subway-panel/applets/window-list/instanceofwindow.cpp:21:
/usr/include/qt4/QtCore/qcoreevent.h:69:9: 錯誤：expected identifier before numeric constant
         None = 0,                               // invalid event
         ^
/usr/include/qt4/QtCore/qcoreevent.h:69:9: 錯誤：expected 「}」 before numeric constant
/usr/include/qt4/QtCore/qcoreevent.h:69:9: 錯誤：expected unqualified-id before numeric constant
In file included from /usr/include/qt4/QtCore/qcoreapplication.h:46:0,
                 from /usr/include/qt4/QtGui/qapplication.h:45,
                 from /usr/include/qt4/QtGui/QApplication:1,
                 from /home/jqk/ProjectFiles/Remote/subway-panel/applets/window-list/../../subway-panel.h:9,
                 from /home/jqk/ProjectFiles/Remote/subway-panel/applets/window-list/window-list.h:29,
                 from /home/jqk/ProjectFiles/Remote/subway-panel/applets/window-list/instanceofwindow.cpp:21:
/usr/include/qt4/QtCore/qcoreevent.h:301:17: 錯誤：expected 「)」 before 「type」
     QEvent(Type type);
                 ^
/usr/include/qt4/QtCore/qcoreevent.h:302:21: 錯誤：「~QEvent」 未宣告為成員
     virtual ~QEvent();
                     ^
/usr/include/qt4/QtCore/qcoreevent.h:303:12: 錯誤：「Type」 沒有命名一個類型
     inline Type type() const { return static_cast<Type>(t); }
            ^
/usr/include/qt4/QtCore/qcoreevent.h:304:31: 錯誤：non-member function 「bool spontaneous()」 cannot have cv-qualifier
     inline bool spontaneous() const { return spont; }
                               ^
/usr/include/qt4/QtCore/qcoreevent.h: In function 「bool spontaneous()」:
/usr/include/qt4/QtCore/qcoreevent.h:304:46: 錯誤：「spont」 在此作用欄位中尚未宣告
     inline bool spontaneous() const { return spont; }
                                              ^
/usr/include/qt4/QtCore/qcoreevent.h: In function 「void setAccepted(bool)」:
/usr/include/qt4/QtCore/qcoreevent.h:306:46: 錯誤：「m_accept」 在此作用欄位中尚未宣告
     inline void setAccepted(bool accepted) { m_accept = accepted; }
                                              ^
/usr/include/qt4/QtCore/qcoreevent.h: At global scope:
/usr/include/qt4/QtCore/qcoreevent.h:307:30: 錯誤：non-member function 「bool isAccepted()」 cannot have cv-qualifier
     inline bool isAccepted() const { return m_accept; }
                              ^
/usr/include/qt4/QtCore/qcoreevent.h: In function 「bool isAccepted()」:
/usr/include/qt4/QtCore/qcoreevent.h:307:45: 錯誤：「m_accept」 在此作用欄位中尚未宣告
     inline bool isAccepted() const { return m_accept; }
                                             ^
/usr/include/qt4/QtCore/qcoreevent.h: In function 「void accept()」:
/usr/include/qt4/QtCore/qcoreevent.h:309:28: 錯誤：「m_accept」 在此作用欄位中尚未宣告
     inline void accept() { m_accept = true; }
                            ^
/usr/include/qt4/QtCore/qcoreevent.h: In function 「void ignore()」:
/usr/include/qt4/QtCore/qcoreevent.h:310:28: 錯誤：「m_accept」 在此作用欄位中尚未宣告
     inline void ignore() { m_accept = false; }
                            ^
/usr/include/qt4/QtCore/qcoreevent.h: At global scope:
/usr/include/qt4/QtCore/qcoreevent.h:314:1: 錯誤：expected unqualified-id before 「protected」
 protected:
 ^
/usr/include/qt4/QtCore/qcoreevent.h:318:1: 錯誤：expected unqualified-id before 「private」
 private:
 ^
/usr/include/qt4/QtCore/qcoreevent.h:320:18: 錯誤：expected initializer before 「:」 token
     ushort spont : 1;
                  ^
/usr/include/qt4/QtCore/qcoreevent.h:321:21: 錯誤：expected initializer before 「:」 token
     ushort m_accept : 1;
                     ^
/usr/include/qt4/QtCore/qcoreevent.h:322:21: 錯誤：expected initializer before 「:」 token
     ushort reserved : 13;
                     ^
/usr/include/qt4/QtCore/qcoreevent.h:324:5: 錯誤：「friend」 used outside of class
     friend class QCoreApplication;
     ^
/usr/include/qt4/QtCore/qcoreevent.h:325:5: 錯誤：「friend」 used outside of class
     friend class QCoreApplicationPrivate;
     ^
/usr/include/qt4/QtCore/qcoreevent.h:326:5: 錯誤：「friend」 used outside of class
     friend class QThreadData;
     ^
/usr/include/qt4/QtCore/qcoreevent.h:327:5: 錯誤：「friend」 used outside of class
     friend class QApplication;
     ^
/usr/include/qt4/QtCore/qcoreevent.h:328:5: 錯誤：「friend」 used outside of class
     friend class QApplicationPrivate;
     ^
/usr/include/qt4/QtCore/qcoreevent.h:329:5: 錯誤：「friend」 used outside of class
     friend class Q3AccelManager;
     ^
/usr/include/qt4/QtCore/qcoreevent.h:330:5: 錯誤：「friend」 used outside of class
     friend class QShortcutMap;
     ^
/usr/include/qt4/QtCore/qcoreevent.h:331:5: 錯誤：「friend」 used outside of class
     friend class QETWidget;
     ^
/usr/include/qt4/QtCore/qcoreevent.h:332:5: 錯誤：「friend」 used outside of class
     friend class QGraphicsView;
     ^
/usr/include/qt4/QtCore/qcoreevent.h:333:5: 錯誤：「friend」 used outside of class
     friend class QGraphicsViewPrivate;
     ^
/usr/include/qt4/QtCore/qcoreevent.h:334:5: 錯誤：「friend」 used outside of class
     friend class QGraphicsScene;
     ^
/usr/include/qt4/QtCore/qcoreevent.h:335:5: 錯誤：「friend」 used outside of class
     friend class QGraphicsScenePrivate;
     ^
/usr/include/qt4/QtCore/qcoreevent.h:337:5: 錯誤：「friend」 used outside of class
     friend class QGestureManager;
     ^
/usr/include/qt4/QtCore/qcoreevent.h:339:1: 錯誤：expected declaration before 「}」 token
 };
 ^
CMakeFiles/subway-panel.dir/build.make:133: recipe for target 'CMakeFiles/subway-panel.dir/applets/window-list/instanceofwindow.cpp.o' failed
make[2]: **\* [CMakeFiles/subway-panel.dir/applets/window-list/instanceofwindow.cpp.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/subway-panel.dir/all' failed
make[1]: **\* [CMakeFiles/subway-panel.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by Icenowy** [comment]
It's a conflict between X11 headers and Qt headers.
